# Page settings

baseurl = "http://www.samuelpartida.org/"
languageCode = "en-us"
title = "Samuel Partida Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Samuel Partida - Public Resume"
    author = "Samuelito Partida"

# Theme styles
    styles = "styles-6.css"

# Sidebar sections
    # Profile section
    [params.profile]
        name = "Samuel Partida"
        tagline = "Systems Engineer & Technical Program Manager"
        avatar = "samuelito.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: samuel.partida AT protonmail.com"
        title = "samuel.partida AT protonmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+41795408675"
        title = "+41 795408675"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/samuel-partida-ba4b4751/"
        title = "LinkedIn"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "https://github.com/elmorti"
        title = "github.com/elmorti"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Computer Science"
        college = "Universitat Oberta de Catalunya"
        dates = "2009 - 2011"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Spanish"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "German"
        level = "Basic"

        [[params.language.list]]
        language = "French"
        level = "Conversational"

        [[params.language.list]]
        language = "Galician"
        level = "Conversational"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Nature"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Skiing"

        [[params.interests.list]]
        interest = "Making"

        [[params.interests.list]]
        interest = "Tinkering"

        [[params.interests.list]]
        interest = "Learning"


# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = "This is Sam, a ***Systems Engineer*** with strong background as ***Technical Program Manager*** both on traditional and Agile project/program management. I have a very long career of more than 20 years in the field, with experience in *Information Security*, *Network Engineering* and *Software Engineering*, ultimately focusing and specializing on the so called ***DevOps*** world."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Site Reliability Engineer"
        dates = "2019 - Present"
        company = "Google, Switzerland"
        details = "DCSW"

        [[params.jobs.list]]
        position = "Technical Program Manager"
        dates = "2014 - 2015"
        company = "Google, Switzerland"
        details = "P2020"

        [[params.jobs.list]]
        position = "Technical Program Manager"
        dates = "2014 - 2015"
        company = "Google, Switzerland"
        details = "P2020"

        [[params.jobs.list]]
        position = "Technical Program Manager"
        dates = "2014 - 2015"
        company = "Google, Ireland"
        details = "P2020"

        [[params.jobs.list]]
        position = "Operations Engineer"
        dates = "2011 - 2015"
        company = "Google, Belgium"
        details = ""

        [[params.jobs.list]]
        position = "System Administrator"
        dates = "2009 - 2011"
        company = "Barclays, Spain"
        details = ""

        [[params.jobs.list]]
        position = "Team Lead"
        dates = "2007 - 2009"
        company = "Soluciones C2, Spain"
        details = ""

        [[params.jobs.list]]
        position = "Team Lead"
        dates = "2006 - 2007"
        company = "Ingenia, Spain"
        details = ""

        [[params.jobs.list]]
        position = "InfoSec Consultant"
        dates = "2005 - 2006"
        company = "Isotrol, Spain"
        details = ""

        [[params.jobs.list]]
        position = "System Administrator"
        dates = "2003 - 2005"
        company = "ECCA, Spain"
        details = ""

        [[params.jobs.list]]
        position = "System Administrator"
        dates = "2001 - 2002"
        company = "Of1gal, Spain"
        details = ""

        [[params.jobs.list]]
        position = "System Administrator"
        dates = "1999 - 2000"
        company = "Cybercenter, Spain"
        details = ""

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Zucchini Universe"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Ansible for Zucchini Universe"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "DevOps"
        level = "100%"

        [[params.skills.list]]
        skill = "Systems Engineering"
        level = "100%"

        [[params.skills.list]]
        skill = "Program Management"
        level = "100%"

        [[params.skills.list]]
        skill = "People Skills"
        level = "100%"

        [[params.skills.list]]
        skill = "Network Engineering"
        level = "75%"

        [[params.skills.list]]
        skill = "Software Engineering"
        level = "50%"

        [[params.skills.list]]
        skill = "Information Security"
        level = "50%"

        [[params.skills.list]]
        skill = "Frontend Development"
        level = "50%"

    # Certifications section
    [params.certifications]
        enable = true
        icon = "fa-certificate"
        title = "Certifications"

        [[params.certifications.list]]
        certificate = "RHCE"

        [[params.certifications.list]]
        certificate = "Prince2"

        [[params.certifications.list]]
        certificate = "MSP"

        [[params.certifications.list]]
        certificate = "SLES 10"

        [[params.certifications.list]]
        certificate = "ITILv2 Foundations"

        [[params.certifications.list]]
        certificate = "SLES 9"

        [[params.certifications.list]]
        certificate = "LPIC 1"

        [[params.certifications.list]]
        certificate = "SSCP"

        [[params.certifications.list]]
        certificate = "Brainbench Linux Administration"

    # Footer section

    [params.footer]
        copyright = "Samuelito Partida"