# Page settings

baseurl = "http://www.samuelpartida.org/"
languageCode = "en-us"
title = "Samuel Partida Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Samuel Partida - Public Resume"
    author = "Samuelito Partida"

# Theme styles
    styles = "styles-6.css"

# Sidebar sections
    # Profile section
    [params.profile]
        name = "Samuel Partida"
        tagline = "Systems Engineer & Technical Program Manager"
        avatar = "samuelito.jpg"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "https://www.linkedin.com/in/samuel-partida-ba4b4751/"
        title = "Samuel Partida"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "https://github.com/elmorti"
        title = "github.com/elmorti"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "BSc in Computer Science"
        college = "Universitat Oberta de Catalunya"
        dates = "2009 - 2011"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Spanish"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        [[params.language.list]]
        language = "German"
        level = "Basic"

        [[params.language.list]]
        language = "French"
        level = "Conversational"

        [[params.language.list]]
        language = "Galician"
        level = "Conversational"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Nature"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Skiing"

        [[params.interests.list]]
        interest = "Making"

        [[params.interests.list]]
        interest = "Tinkering"

        [[params.interests.list]]
        interest = "Learning"

        [[params.interests.list]]
        interest = "Gaming"


# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "About"
        summary = "Hello! I am Sam, a ***Systems Engineer*** with strong background as ***Technical Program Manager*** both on traditional and *Agile project/program management*. I have a very long career of more than 20 years in the field, with experience in ***Information Security***, ***Network Engineering*** and ***Software Engineering***, ultimately focusing and specializing on the so called ***DevOps*** world. My ideal job is the one __where I can leverage the skills of my team__. I love tinkering with tangible and non-tangible technical things, gaming and making my own candles."

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Site Reliability Engineer - Datacenter Software"
        dates = "2019 - Present"
        company = "Google, Switzerland"
        details = "As part of the DCSW team, my work is to ensure the **best onboarding of critical Google Datacenter infrastructure services** to the best standards of Google Production, I contribute to ***improve our onboarded services release management, defining SLOs, alerting, monitoring and developing maintenance and incident documentation***. More particularly I am *specialized in end to end black box monitoring and probing of our services and their dependencies.*"

        [[params.jobs.list]]
        position = "Technical Program Manager - Google Cloud"
        dates = "2018 - 2019"
        company = "Google, Switzerland"
        details = "As part of Cloud, I drove the **integration of Cloud and internal infrastructure technologies** program, bridging the gap between our tech island and the external cloud services. Particularly I achieved the ***integration of Google Kubernetes Engine with our internal infrastructure, our engineers can now choose to run Google services on top the GKE platform.***"

        [[params.jobs.list]]
        position = "Technical Program Manager - Google Lens"
        dates = "2017 - 2018"
        company = "Google, Switzerland"
        details = "As part of Google Lens, I drove the development of the *LVS software*, the middleware for Google Lens that **implements an API and bridges our imaging and knowledge backends with the end user applications** to analyze images and videos and provide the final information and annotations."

        [[params.jobs.list]]
        position = "Technical Program Manager - DCNet"
        dates = "2015 - 2017"
        company = "Google, Ireland"
        details = "As part of DCNet, I **led the Datacenter and Network Infrastructure deployment program for the Google DC Campuses of Belgium, Finland and Ireland.** Driving the projects to ***turn up megawatts of machine clusters and kilometers of fiber for our DC network, both customer facing and backbone inter-site networks.***"

        [[params.jobs.list]]
        position = "Operations Engineer - Hardware Operations"
        dates = "2011 - 2015"
        company = "Google, Belgium"
        details = "As part of Hardware Operations, I **led the team responsible to execute the daily operations of the Google Datacenter in Belgium**, involving **machine and network repairs, cluster turn ups, expansions, qa and decommissioning.***"

        [[params.jobs.list]]
        position = "System Administrator"
        dates = "2009 - 2011"
        company = "Barclays, Spain"
        details = "As part of Middle Services, I was **responsible of the design, operation and maintenance of the SAN across the offices of Madrid and Zaragoza, Spain.** Designing the layout of the storage cabinets, automating the assignment of FC ports, LUNs, tailoring different storage solutions to the services. ***I developed the inter-site DR/BC program.***"

        [[params.jobs.list]]
        position = "Team Lead"
        dates = "2007 - 2009"
        company = "Soluciones C2, Spain"
        details = "As part of Systems Department, I **led the team responsible of the design, operation and maintenance of our production servers for our customers**, ensuring their hosted websites were on SLA, maintaning and operating our in-house backup system, ***I also designed and implement a custom CI/CD for our full-stack developers.***"

        [[params.jobs.list]]
        position = "Team Lead"
        dates = "2006 - 2007"
        company = "Ingenia, Spain"
        details = "As part of the Public Administartion Business Unit, I was **in charge of the team of systems administrators for the complete renovation of the data backend system for the Public Water Management company in Sevilla, Spain.** The deployment consisted of ***frontend machines with RHEL, backend Oracle cluster (Oracle GRID) and F5 firewall and IPS appliances.***"

        [[params.jobs.list]]
        position = "InfoSec Consultant"
        dates = "2005 - 2006"
        company = "Isotrol, Spain"
        details = "As part of Pentest team, I was **responsible of routinely execute penetration tests for our clients, mainly Public Administration offices, then analyzing the results, compiling and providing a full report** of the findings and proposing solutions to harden the vulnerable services."

        [[params.jobs.list]]
        position = "System Administrator"
        dates = "2003 - 2005"
        company = "ECCA, Spain"
        details = "ECCA is a Spanish non-profit organization that aims to provide free education and training for adult people, I was hired to **design, operate and maintain the IT infrastructure for the headquarters in Sevilla.** From network design to implementation and deployment of a centralized in-house Samba DC for the employees, providing centralized remote user profiles, secure email services and automated software deployment. I also provided basic IT training courses."

        [[params.jobs.list]]
        position = "Computer Assembler"
        dates = "2001 - 2002"
        company = "Of1gal, Spain"
        details = "As part of the IT department, I was in charge of assembling **customized and optimized GNU/Linux servers for schools and SOHO businesses**, and at the same time providing tech support."

        [[params.jobs.list]]
        position = "Tech Support"
        dates = "2001 - 2002"
        company = "Banco Pastor, Spain"
        details = "As part of the credit card department, I was in charge of providing **tech support on the backend system managing card and credit approvals** running on the bank mainframe."

        [[params.jobs.list]]
        position = "Clerk and Tech Support"
        dates = "1999 - 2000"
        company = "Cybercenter, Spain"
        details = "One man team in charge of the **designing and deployment of a cyber-cafe network of PCs** for customers to sit, browse and play games, as well as being the clerk."

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Projects"
        intro = "To keep myself up to date with the current state of the art in the field, I spend some time with **my own personal projects.**"

        [[params.projects.list]]
        title = "Zucchini Universe"
        url = "https://www.zucchiniuniverse.org"
        tagline = "Zucchini Universe is an **umbrella project** where me and my [wife](https://www.sanemsay.org) **create gaming worlds and environments aiming to grow a healthy community of gamers around the world**. Everything we do is ***non-profit and open source.***"

        [[params.projects.list]]
        title = "Ansible for Zucchini Universe"
        url = "https://github.com/elmorti/zucchini-ansible"
        tagline = "I am building, stone by stone, a set of **Ansible roles for the provisioning, maintenance and hardening of our servers and services.** I make them publicy available so others can benefit from it as I did from others. From simple server provisioning to a *full deployment of a test Kubernetes cluster* and more."

        [[params.projects.list]]
        title = "Containers for Zucchini Universe"
        url = "https://github.com/elmorti/zucchini-containers"
        tagline = "As with Ansible, this is my share of **system containers** that I use on our infrastructure, some are more mature than others but they are quite useful. From an open-source Minecraft server manager to *monitoring systems with **Prometheus** and **Grafana***, here I keep all the container files for my services."

        [[params.projects.list]]
        title = "Vagrant for Zucchini Universe"
        url = "https://github.com/elmorti/zucchini-vagrant"
        tagline = "My **Vagrant recipes for development** are also shared to everyone. I use them everyday for testing new things, tinkering and development. *Environments to use and discard.*"

        [[params.projects.list]]
        title = "Zucchini Universe - Empyrion Galactic Survival"
        url = "https://github.com/elmorti/zucchini-empyrion"
        tagline = "One of our main gaming communities, built around Empyrion Galactic Survival. I have built an infrastructure over Hetzner Online dedicated servers, **Windows Server 2019** and a custom game scenario, contents and rules. I also develop **game extensions on C#.** Operations are done remotely over a **secure Wireguard VPN, monitoring with Prometheus and a Windows node exporter and custom backup and release automation with Powershell magic.**"

        [[params.projects.list]]
        title = "Zucchini Universe - ARK Survival Evolved"
        url = "https://github.com/elmorti/zucchini-ark"
        tagline = "Our other community and our first one, ARK Survival Evolved. Also with infrastructure from Hetzner Online dedicated servers, **Windows Server 2019**, custom game settings, contents and rules. I developed a great set of **automation tools in Python.** Operations are done remotely over a **secure Wireguard VPN, monitoring with Prometheus and a Windows node exporter and custom backup and release automation with Powershell magic.**"

        [[params.projects.list]]
        title = "Zucchini Universe - Minecraft"
        url = "https://panel.zucchiniuniverse.org/"
        tagline = "The other gaming community is mostly led by my son, and it consists of many Minecraft servers. I manage the infrastructure behind, also a dedicated server from Hetzner Online, **CentOS 8 GNU/Linux** and completely running the services in **containers managed by Podman.** Remote administration is also via **Wireguard VPN, monitoring with Prometheus** as well and my own backup system with Bash magic. The **frontend is a Laravel app with MariaDB and Redis backend and NGINX https server.**"

        [[params.projects.list]]
        title = "Godot Projects"
        url = "https://github.com/elmorti/lousymarioclone"
        tagline = "Sometimes I dream of creating my own videogame, so I started **learning with Godot.** You can checkout some of my... work."

        [[params.projects.list]]
        title = "Technical Notes"
        url = "https://www.elmorti.org"
        tagline = "This is my personal technical blog, I try my best to publish every **experiments, discoverings, and tech tips** I use every day or so."


    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "DevOps"
        level = "100%"

        [[params.skills.list]]
        skill = "Systems Engineering"
        level = "100%"

        [[params.skills.list]]
        skill = "Program Management"
        level = "100%"

        [[params.skills.list]]
        skill = "People Skills"
        level = "100%"

        [[params.skills.list]]
        skill = "Network Engineering"
        level = "75%"

        [[params.skills.list]]
        skill = "Software Engineering"
        level = "75%"

        [[params.skills.list]]
        skill = "Information Security"
        level = "75%"

        [[params.skills.list]]
        skill = "Frontend Development"
        level = "75%"

    # Certifications section
    [params.certifications]
        enable = true
        icon = "fa-certificate"
        title = "Certifications"

        [[params.certifications.list]]
        certificate = "Managing Successful Programmes (Foundations & Practitioner)"

        [[params.certifications.list]]
        certificate = "PRINCE2 (Foundations & Practitioner)"

        [[params.certifications.list]]
        certificate = "Red Hat Certified Engineer 5"

        [[params.certifications.list]]
        certificate = "SuSE Linux Enterprise Server 10"

        [[params.certifications.list]]
        certificate = "SuSE Linux Enterprise Server 9"

        [[params.certifications.list]]
        certificate = "ITILv2 Foundations"

        [[params.certifications.list]]
        certificate = "Linux Professional Institute LPIC 1"

        [[params.certifications.list]]
        certificate = "ISC2 Systems Security Certified Practitioner"

        [[params.certifications.list]]
        certificate = "Brainbench Linux Administration"

    # Footer section

    [params.footer]
        copyright = "Samuelito Partida"